version: '3'
services:
  backend:
    build: .
    container_name: rust_sample_backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    tty: true

  postgres:
    build: ./.docker/postgres
    container_name: postgres_rust_sample
    tty: true
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample_service
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - sample_service

volumes:
  rustapp:
    driver: local

networks:
  sample_service: